# Generated by Django 3.1.3 on 2020-11-30 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
