# Generated by Django 3.1.3 on 2020-11-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, default='Common', max_length=300, null=True)),
                ('language', models.CharField(blank=True, default='English', max_length=300, null=True)),
                ('description', models.CharField(default='a', max_length=3000)),
                ('sub_name', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('link', models.CharField(blank=True, default='', max_length=300, null=True)),
            ],
        ),
    ]
