# Generated by Django 3.1.3 on 2020-12-01 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0004_testfeeditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testfeeditem',
            name='user_profile',
        ),
    ]
