# Generated by Django 3.1.3 on 2020-12-01 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0005_remove_testfeeditem_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testfeeditem',
            old_name='status_text',
            new_name='status',
        ),
    ]
