# Generated by Django 3.1.3 on 2020-12-01 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0006_auto_20201201_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testfeeditem',
            old_name='status',
            new_name='feed_text',
        ),
    ]
